name: Render

on:
  workflow_dispatch:
    inputs:
      video:
        description: 'link video'
        required: true
      subs:
        description: 'link subtitle'
        required: false

jobs:
  render-video:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release
          cache-hit: true

      - run: |
          sudo apt-get update
          sudo apt-get install -y fonts-nanum
      - run: |
          wget -O video.mp4 "${{ github.event.inputs.video }}"
          wget -O sub.ass "${{ github.event.inputs.subs }}"

          ffmpeg -y \
            -i video.mp4 \
            -i audio.mp3 \
            -vf "ass=sub.ass" \
            -c:v libx264 -preset fast -crf 23 \
            out.mp4

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: video-output
          path: output.mp4
