name: Docker

on:
  push:
    branches: [ "main" ]
    paths:
      - "dockerbox/render/Dockerfile"

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write 
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build + push image
      - name: Build & Push
        run: |
          docker build -t ghcr.io/${{ github.repository }}/render:latest -f dockerbox/render/Dockerfile .
          docker push ghcr.io/${{ github.repository }}/render:latest