name: Render

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'Dockerfile'

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Compute params hash
        id: hash
        run: echo "hash=$(sha256sum params.env | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release

      - run: |
          sudo apt-get install -y fonts-nanum || true
      
      - name: Load params
        run: |
          run: cat params.env >> $GITHUB_ENV

      - name: Exectute
        run: |
          wget -O clips.zip "$CLIPS"
          unzip clips.zip -d clips

          wget -O sub.txt "$SUBS"
          wget -O audio.mp3 "$AUDIO"

          python render.py





      
