name: Render

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'Dockerfile'
    # paths:
      # - "params.env"

  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/tokhacnhi/render/render:latest

    steps:
      - uses: actions/checkout@v5
      - name: run
        run: python render.py

          





      
