name: Render

on:
  workflow_dispatch:
    inputs:
      video:
        description: 'link video'
        required: true
      subs:
        description: 'link subtitle'
        required: false

jobs:
  render-subtitle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release

      - run: |
          sudo apt-get update
          sudo apt-get install -y fonts-nanum
          
      - run: |
          wget -O video.mp4 "${{ github.event.inputs.video }}"
          wget -O sub.ass "${{ github.event.inputs.subs }}"

          ffmpeg -y \
            -i video.mp4 \
            -vf "ass=sub.ass" \
            -c:v libx264 -preset fast -crf 23 \
            output.mp4

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE }}

      - name: Upload
        run: |
          UUID=$(uuidgen)
          rclone copy output.mp4 r2:n8n/${UUID}.mp4
          echo "Uploaded as ${UUID}.mp4"
