name: Render

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dockerbox/**'
    # paths:
      # - "params.env"

  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/tokhacnhi/render/render:latest

    outputs:
      webhook: ${{ steps.task.outputs.webhook }}  # map step output sang job output
      result: ${{ steps.task.outputs.result }}

    steps:
      - uses: actions/checkout@v5
      - name: run
        id: task
        run: |
          echo $(curl -s "http://ip-api.com/json/" | jq -r '"\(.query) | \(.country) | \(.city)"')

          WEBHOOK=$(jq -r '.webhook' params/render.json)
          RAW_DATA=$(python render.py)
          echo "RAW_DATA = $RAW_DATA"

          echo "webhook=$WEBHOOK" >> $GITHUB_OUTPUT
          echo "result=$RAW_DATA" >> $GITHUB_OUTPUT

  error:
      runs-on: ubuntu-latest
      needs: render
      if: failure()
      steps:
        - name: Send webhook
          run: |
            curl -X POST -H "Content-Type: application/json" \
              -d "{\"status\":\"fail\",\"data\": null}" \
              "$WEBHOOK"
            





      
