name: Render

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'Dockerfile'
    # paths:
      # - "params.env"

  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/tokhacnhi/render/render:latest

    steps:
      - uses: actions/checkout@v5

      - name: Exectute
        run: |
          cat params.env >> $GITHUB_ENV
          wget -O clips.zip "$CLIPS"
          unzip clips.zip -d clips

          wget -O sub.txt "$SUBS"
          wget -O audio.mp3 "$AUDIO"

          python render.py





      
