name: Render

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dockerbox/**'
    # paths:
      # - "params.env"

  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/tokhacnhi/render/render:latest

    outputs:
      webhook: ${{ steps.task.outputs.webhook }}  # map step output sang job output
      render_data: ${{ steps.task.outputs.data }}
      
    steps:
      - uses: actions/checkout@v5
      - name: run
        id: task
        run: |
          WEBHOOK=$(jq -r '.webhook' params/render.json)
          echo "webhook=$WEBHOOK" >> $GITHUB_OUTPUT
          echo "WEBHOOK = $WEBHOOK"
          
          RAW_JSON=$(python render.py)
          DATA=$(echo "$RAW_JSON" | base64)
          echo "data=$DATA" >> $GITHUB_OUTPUT

  notify:
      runs-on: ubuntu-latest
      needs: render
      if: always()
      steps:
        - name: Send webhook
          run: |
            STATUS="success"
            if [ "${{ needs.render.result }}" != "success" ]; then
              STATUS="failure"
            fi

            WEBHOOK="${{ needs.render.outputs.webhook }}"

            echo 
            DATA="${{ needs.render.outputs.render_data }}"

            if [ -n "$DATA" ]; then
              DECODED=$(echo "$DATA" | base64 --decode)
            else
              DECODED=""
            fi

            echo "WEBHOOK = ${{ needs.render.outputs.webhook }}"
            echo "DATA = $DECODED"

            curl -X POST -H "Content-Type: application/json" \
              -d "{\"status\":\"$STATUS\",\"data\":$DECODED}" \
              "$WEBHOOK"
            





      
