name: Render

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dockerbox/**'
    # paths:
      # - "params.env"

  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/tokhacnhi/render/render:latest

    outputs:
      webhook: ${{ steps.task.outputs.webhook }}  # map step output sang job output
      data: ${{ steps.task.outputs.data }}

    steps:
      - uses: actions/checkout@v5
      - name: run
        id: task
        run: |
          echo $(curl -s "http://ip-api.com/json/" | jq -r '"\(.query) | \(.country) | \(.city)"')
          pip install fire

          WEBHOOK=$(jq -r '.webhook' params/render.json)
          echo "webhook=$WEBHOOK" >> $GITHUB_OUTPUT
          echo "WEBHOOK = $WEBHOOK"
          
          RAW_DATA=$(python render.py)
          echo "RAW_DATA: $RAW_DATA"
          DATA=$(echo "$RAW_DATA" | base64 -w0)
          
          echo "DATA: $DATA"
          echo "data=$DATA" >> $GITHUB_OUTPUT

  notify:
      runs-on: ubuntu-latest
      needs: render
      if: always()
      steps:
        - name: Send webhook
          run: |
            STATUS="success"
            if [ "${{ needs.render.result }}" != "success" ]; then
              STATUS="failure"
            fi

            WEBHOOK="${{ needs.render.outputs.webhook }}"
            DATA="${{ needs.render.outputs.data }}"

            curl -X POST -H "Content-Type: application/json" \
              -d "{\"status\":\"$STATUS\",\"data\": \"$DATA\"}" \
              "$WEBHOOK"
            





      
